### ISSUE TITLE
Mistake in documentation at npmjs

### ISSUE THREAD

**Issue by HeeL** [holidaycheck/healthcheck-ping#37]
README on npmjs is not in sync with github:
https://www.npmjs.com/package/healthcheck-ping

It suggests to require module like this:
`var createHealthcheckMiddleware = require('healthcheck-middleware');`

This throw that module was not found. It has to be changed to:
`var createHealthcheckMiddleware = require('healthcheck-ping');`

**Comment by screendriver** [comment]
This was fixed in dde91207f46bb88935efc3338baab4bdaed7fa4e
